---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, Inc."
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

???

```{r echo=FALSE, message=TRUE}
use_theme_github = function(theme = "tcgriffith/xaringan_theme_example", ref =
                              "master") {
  bn = basename(theme)
  
  repo = paste0("https://github.com/", theme)
  
  

  cmd = paste0("git ls-remote ",repo," refs/heads/master")
  rslt = system(command=cmd, intern=TRUE)
  ref = stringr::str_sub(rslt, 1,8)
  
  message("# Theme repo:", repo)
  message("# ref: ", ref)
  message(sprintf("# To use the same theme, try use_theme_github(%s,%s)",theme, ref))

  css_remote = paste0("https://raw.githubusercontent.com/",
                      theme,
                      "/",
                      ref,
                      "/",
                      bn,
                      ".css")
  
  css_local = basename(css_remote)
  xfun::download_file(css_remote)
  htmltools::includeCSS(css_local)
}

use_theme_github("tcgriffith/xaringan_theme_example")
```





---

## use_theme!



```{r}


```


---

background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/be/Sharingan_triple.svg)

???

Image credit: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Sharingan_triple.svg)

---
class: center, middle

# xaringan

### /ʃaː.'riŋ.ɡan/


---
class: bg-red

# I am red!


---
class: bg-bisque

# I am bisque!

---
class: bg-blue

# I am blue, 

# if it's not blue, you are using an old version of the theme!

the init version doesn't have blue!



